# 이 파일을 application-secret.yaml로 복사한 뒤 ** 부분만 수정하세요.
database:
  username: "**"
  password: "**"

openvidu:
  url: OPENVIDU_SERVER_URL
  secret: OPENVIDU_SERVER_SECRET
  webhook-secret: OPENVIDU_WEBHOOK_SECRET

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: YOUR_BUCKET_NAME
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY
