# 이 파일을 application-secret.yaml로 복사한 뒤 ** 부분만 수정하세요.
database:
  username: "**"
  password: "**"

openvidu:
  url: OPENVIDU_SERVER_URL
  secret: OPENVIDU_SERVER_SECRET
  webhook-secret: OPENVIDU_WEBHOOK_SECRET
